MULTIPLE_ALIGNMENT_FINISHED = 'MULTIPLE_ALIGNMENT_FINISHED'
PROCESS_TASK = 'process_alignment'
MULTIPLE_ALIGNER_TASK = 'multiple_aligner'
PROCESS_QUEUE = 'server_aligner'
MULTIPLE_ALIGNER_QUEUE = 'server_comparer'
QUEUE_DISPATCHER = {
    PROCESS_TASK: PROCESS_QUEUE,
    MULTIPLE_ALIGNER_TASK: MULTIPLE_ALIGNER_QUEUE,
}